# Generated by Django 4.0.2 on 2022-02-12 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('reason', models.CharField(max_length=254, unique=True)),
                ('use', models.CharField(max_length=254)),
                ('date', models.CharField(max_length=30)),
                ('hour', models.CharField(max_length=30)),
                ('phone', models.IntegerField(max_length=10, null=True)),
            ],
        ),
    ]
