# Generated by Django 4.0.2 on 2022-03-30 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0005_testing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testing',
            old_name='uname',
            new_name='username',
        ),
    ]
