# Generated by Django 4.0.2 on 2022-03-30 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0007_rename_testing_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('pwd', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='test',
        ),
    ]
