# Generated by Django 4.0.2 on 2022-03-30 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0008_prueba_delete_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='prueba',
        ),
    ]
