# Generated by Django 4.0.4 on 2022-04-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0010_testing'),
    ]

    operations = [
        migrations.CreateModel(
            name='testfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('uploaded', models.FileField(upload_to='upload/')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
