# Generated by Django 4.0.4 on 2022-04-25 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0012_alumnos_ejercicios_maestros_evaluaciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='passwd',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='maestros',
            name='passwd',
            field=models.CharField(max_length=254),
        ),
    ]
