# Generated by Django 4.0.4 on 2022-05-02 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0013_alter_alumnos_passwd_alter_maestros_passwd'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnos',
            name='idMaestro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modelo.maestros'),
        ),
    ]
