# Generated by Django 4.0.4 on 2022-05-08 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0015_alumnos_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.CharField(blank=True, max_length=254)),
                ('turno', models.CharField(blank=True, max_length=254)),
                ('initDate', models.CharField(max_length=60)),
                ('finalDate', models.CharField(max_length=60)),
                ('idAlumno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modelo.alumnos')),
                ('idMaestro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modelo.maestros')),
            ],
        ),
    ]
