# Generated by Django 4.0.4 on 2022-05-19 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0016_grupo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='idAlumno',
        ),
    ]
