# Generated by Django 4.0.4 on 2022-06-08 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0017_remove_grupo_idalumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicios',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
