# Generated by Django 4.0.4 on 2022-06-09 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0019_alter_evaluaciones_calificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluaciones',
            name='intentos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
