# Generated by Django 4.0.4 on 2022-06-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0020_alter_evaluaciones_intentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluaciones',
            name='calificacion',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
